-- ==========================================
-- COMPLETE SUPABASE SETUP SCRIPT
-- ==========================================

-- 0. ENABLE UUID EXTENSION (required for attendance IDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. CREATE STUDENTS TABLE
CREATE TABLE IF NOT EXISTS students (
    roll_number TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. CREATE ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS attendance (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    roll_number TEXT REFERENCES students(roll_number) ON DELETE CASCADE,
    date DATE NOT NULL,
    hours NUMERIC DEFAULT 0,
    scanned_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(roll_number, date)
);

-- 3. ENABLE ROW LEVEL SECURITY
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICIES (Allow public access for now since this is a frontend-only app)
CREATE POLICY "Allow public read access on students" ON students FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on students" ON students FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access on attendance" ON attendance FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on attendance" ON attendance FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access on attendance" ON attendance FOR DELETE USING (true);
CREATE POLICY "Allow public update access on attendance" ON attendance FOR UPDATE USING (true);

-- 5. SEED STUDENTS DATA
INSERT INTO students (roll_number, name) VALUES
('CB.AI.U4AID25009', 'Bojanala Surya Charan Tej'),
('CB.AI.U4AID25031', 'MOORTHY NEERAJ'),
('CB.AI.U4AID25025', 'KONDAPALLI BHANU PRAKASH'),
('CB.AI.U4AID25061', 'YETURU PRANAVI REDDY'),
('CB.AI.U4AID25032', 'MORTHA SATHWIK'),
('CB.AI.U4AID25046', 'S V PAVAN KALYAN'),
('CB.AI.U4AID25007', 'Balam Sharmitha'),
('CB.AI.U4AID25011', 'CHUKKALURU JASMITHA'),
('CB.AI.U4AID25067', 'GHADIGE RITHIKA'),
('CB.AI.U4AID25141', 'Pervela Phani Shankara Manvith Sharma'),
('CB.AI.U4AID25111', 'BOVILLA LALITH HARI SAINATH REDDY'),
('CB.AI.U4AID25145', 'R Gagan Chowdary'),
('CB.AI.U4AID25112', 'C Saihardhik Reddy'),
('CB.AI.U4AID25124', 'Kavali Charan Saatvikh Reddy'),
('CB.AI.U4AID25130', 'MALIKIREDDY PRANAVI'),
('CB.AI.U4AID25153', 'SUTHASRINITHA K G'),
('CB.AI.U4AID25132', 'MIRUDHUNYA V'),
('CB.SC.U4AIE25001', 'ABDUL JABBAR M'),
('CB.SC.U4AIE25009', 'DABBUGOTTU NAGA PARDHU YADAV'),
('CB.SC.U4AIE25025', 'M ASHWIN KUMAR'),
('CB.SC.U4AIE25047', 'SHREYA SARAVANAN'),
('CB.SC.U4AIE25018', 'Harishmitha R'),
('CB.SC.U4AIE25066', 'SAKSHI'),
('CB.SC.U4AIE25116', 'GANGIREDDY SUKESWAR REDDY'),
('CB.SC.U4AIE25137', 'NADIMPALLI KARTHIKEYA VARMA'),
('CB.SC.U4AIE25115', 'DONTHU DHEERAJ SIMHA'),
('CB.SC.U4AIE25114', 'DHARINI K B'),
('CB.SC.U4AIE25145', 'RITHIKA MUTHUKUMAR'),
('CB.SC.U4AIE25163', 'YUTHIKA SRI J'),
('CB.AI.U4AIM25001', 'Aadithya Ram'),
('CB.AI.U4AIM25041', 'Umasuthan Palaniappan'),
('CB.AI.U4AIM25049', 'Hrithick.B'),
('CB.AI.U4AIM25045', 'CHAGANTI SESI KARTHIK'),
('CB.AI.U4AIM25004', 'CHAGANTI SAI MANIKANTA PAPAYYA CHOWDARY'),
('CB.AI.U4AIM25007', 'CHAGANTI SAI MANIKANTA PAPAYYA'),
('CB.AI.U4AIM25016', 'Karumuri Harshitha Snigdha'),
('CB.AI.U4AIM25042', 'VABILISETTY JAHNAVI DEVI'),
('CB.AI.U4AIM25010', 'HARINI S'),
('CB.AI.U4AIM25014', 'JOSHIKA C D'),
('CB.AI.U4AIM25038', 'SHRITHANISHKA S'),
('CB.AI.U4AAR25028', 'MAHESWARLA PAVAN SAI'),
('CB.AI.U4AAR25033', 'NELLORE HEMAKSHARA KARTHIKEYA SINGH'),
('CB.AI.U4AAR25047', 'SANDIRI SHREE VARDHAN'),
('CB.AI.U4AAR25007', 'ARUNITHA SUDEV'),
('CB.AI.U4AAR25023', 'Kashish Mehra'),
('CB.AI.U4AAR25057', 'VARSHINI R V'),
('CB.AI.U4CPS25014', 'DHIREN VASUDEVA'),
('CB.AI.U4CPS25059', 'ANNAREDDY PARDHAV REDDY'),
('CB.AI.U4CPS25055', 'Vinith tiwari'),
('CB.AI.U4CPS25034', 'PALELLA BHANU PRASAD'),
('CB.AI.U4CPS25046', 'SATTINENI VENKATA SATYA TULASI RAM'),
('CB.AI.U4CPS25012', 'Chunduru venkata abhiram'),
('CB.AI.U4CPS25027', 'Mahizha S'),
('CB.AI.U4CPS25018', 'Gullanki Bhagya Lakshmi'),
('CB.AI.U4CPS25031', 'Nehasri Mullapudi'),
('CB.AI.U4CPS25051', 'VANI SHIVAJA KARRE'),
('CB.AI.U4QTS25017', 'CHITTURU LOKESH'),
('CB.AI.U4QTS25035', 'pamuri yuvacharan'),
('CB.AI.U4QTS25051', 'BHEEMIREDDY NIHALESHWAR REDDY'),
('CB.AI.U4QTS25053', 'SIDDAMREDDY JEEVAN REDDY'),
('CB.AI.U4QTS25016', 'Chittoor Kuppaswamy Sai Jitesh'),
('CB.AI.U4QTS25048', 'Vismay A'),
('CB.AI.U4QTS25011', 'Bezawada Saitanusha'),
('CB.AI.U4QTS25049', 'VUYYURI HEMA SREE'),
('CB.AI.U4QTS25021', 'G BHAVYA')
ON CONFLICT (roll_number) DO UPDATE SET name = EXCLUDED.name;
